//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354_Group_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFurniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFurniture()
        {
            this.tblClientFurnitures = new HashSet<tblClientFurniture>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int typeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClientFurniture> tblClientFurnitures { get; set; }
        public virtual tblFurnitureType tblFurnitureType { get; set; }
    }
}
